### ISSUE TITLE
i cannot install 

### ISSUE THREAD

**Issue by crusj** [Mitscherlich/hexo-theme-amber#1]
i very like your theme ,can you add fixed sidebar for makedoc TOC,thank you !

**Comment by Mitscherlich** [comment]
Thank for comment. TOC is now in schedule but it may take some time. 
Would you provide more detail of installation failure so may be I can help you?

**Comment by crusj** [comment]
I have install it, but it has many warning, l visit your.blog, i find it has a difference such as it has no scroll top button

**Comment by Mitscherlich** [comment]
😅 Sorry about that. The **STT** button is added by my [CDN](https://www.cloudflare.com/) and may not be added in the future.

And if it is an **npm** warning, it's just that some *peerDependencies* are not installed and can be ignored. If it is a **vue** warning, it means that one or several files *exceed the recommended size*, and can also be ignored.

If these won't help, please provide console log and I am willing to help you.

**Comment by crusj** [comment]
Just some npm warnings, Thank you.
