### ISSUE TITLE
安装报错啊

### ISSUE THREAD

**Issue by elarbor** [Mitscherlich/hexo-theme-amber#14]
![image](https://github.com/Mitscherlich/hexo-theme-amber/assets/43592730/3331982e-7ad8-494d-bfe8-3d020aaef75b)

**Comment by Mitscherlich** [comment]
windows 不支持 symbol link，使用 git 方式安装此主题:

```bash
$ cd <你的博客根路径>
$ git clone -b deploy https://github.com/Mitscherlich/hexo-theme-amber.git --depth=1 themes/amber
```

btw 这个主题很久没有维护了，不保证跟随了最新的 hexo 特性，不确定是否兼容。
