### ISSUE TITLE
轮播图无法显示图片

### ISSUE THREAD

**Issue by FelixHolmes** [Mitscherlich/hexo-theme-amber#3]
轮播图显示不出来图片？

**Comment by FelixHolmes** [comment]
已经解决,图片必须来自与网络。

**Comment by Mitscherlich** [comment]
轮播图和 fancybox 的图片必须放在 source/assets 文件夹下或存在于网络上，这是由于 vue 调试时这些资源文件是通过 webpack proxy 从 hexo-server 获取的

感谢反馈，文档将在下一个提交得到完善
