### ISSUE TITLE
代码片段显示不全

### ISSUE THREAD

**Issue by huqianshan** [Mitscherlich/hexo-theme-amber#6]
### 1 当一行代码过长时 显示不全 
![Snipaste_2019-01-28_22-52-00.png](https://i.loli.net/2019/01/28/5c4f17239f2f0.png)

### 2 首页轮播图效果不是很理想

 很喜欢博主这个设想 但是似乎实际展示效果并不怎么好 貌似动漫图片效果可以 其他类型图片就#### e 可能就是图片尺寸不适配吧 要是博主有好的解决办法就好啦

**Comment by Mitscherlich** [comment]
你好，代码片段是可以横向滚动的。

关于轮播图，我的策略是取文章中的第一张图片作为头图，如果图片不理想，可以在文章头部添加 cover: [path] 来设置一张 16:9 的图片作为头图。

当然我也一直在寻找更好的适配方案，感谢你对本主题的支持🙏，近期会有小幅更新，敬请关注😊

**Comment by huqianshan** [comment]
thanks 
原来可以根据小键盘移动的，，，√
感谢博主的开发：）
