### ISSUE TITLE
如何去除主页图片轮播模块

### ISSUE THREAD

**Issue by huqianshan** [Mitscherlich/hexo-theme-amber#7]
如何去除主页图片轮播模块

- 发现有些post的图片不适合放在框中，想直接去掉这个模块。该如何修改文件呢？ 主题其他的配置都很喜欢

**Comment by Mitscherlich** [comment]
https://github.com/Mitscherlich/hexo-theme-amber/blob/5ec1e19208c86ade18e87d6a5c50a435e9a387c0/_config.yml#L14

这一行设为 `false` 就可以了
